export let customPerfPTC1 = {
  type: 'perf1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu thuần',
      dataKey: 'doanhSoThuan',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận ròng',
      dataKey: 'loiNhuanCuaCoDongCongTyMe',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: ' Biên lợi nhuận gộp',
      dataKey: 'bienLaiGop',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Biên lợi nhuận ròng',
      dataKey: 'bienLaiRong',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, showLineReference: true, divide: 2 },
    right: { type: 'per', piecewise: true },
  },
};
export let customPerfPTC2 = {
  type: 'perf2',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Hoạt động kinh doanh',
      dataKey: 'loiNhuanCotLoi',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Hoạt động tài chính',
      dataKey: 'loiNhuanTaiChinh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khác',
      dataKey: 'thuNhapKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Từ Công ty LDLK',
      dataKey: 'laiLoTuCongTyLienDoanh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true, showLineReference: true },
  },
};
export let customPerfPTC3 = {
  type: 'perf3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu TTM',
      dataKey: 'salesTrailing',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Lợi nhuận gộp TTM',
      dataKey: 'gpmtrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Chi phí vận hành TTM',
      dataKey: 'sgamtrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'EBIT Margin TTM',
      dataKey: 'ebitmTrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CFAB6D',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'per', piecewise: true },
  },
};
export let customPerfPTC4 = {
  type: 'perf4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'EBIT TTM',
      dataKey: 'ebittrailing',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
      // highlightScope: {
      //   highlighted: 'item',
      //   faded: 'global',
      // },
    },
    {
      type: 'bar',
      label: 'Lợi nhuận tài chính TTM',
      dataKey: 'netFinanceialTrailing',
      yAxisId: 'leftAxis',
      color: '#6EA2DF',
      changeColor: true,
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'EBIT Margin TTM',
      dataKey: 'ebitmTrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CFAB6D',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Biên lợi nhuận ròng TTM',
      dataKey: 'nimgTrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: {
      type: 'bil',
      piecewise: true,
      showLineReference: true,
      divide: 2,
      // nagative: true,
      // colors: ['#6EA2DF', '#981F36'],
      // colorsBasic: ['#C8D0D2'],
    },
    right: { type: 'per', piecewise: true },
  },
};
export let customPerfPTC5 = {
  type: 'perf5',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận ròng TTM',
      dataKey: 'nitrailing',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi ích cổ đông thiểu số TTM',
      dataKey: 'minoritiesTrailing',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận CTLDLK TTM',
      dataKey: 'associateTrailing',
      yAxisId: 'rightAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: false, showLineReference: true, opacity: 2 },
  },
};
export let customPerfPTC6 = {
  type: 'perf6',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'EBITDA TTM',
      dataKey: 'ebitdatrailing',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'EBIT TTM',
      dataKey: 'ebittrailing',
      yAxisId: 'leftAxis',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lãi vay TTM',
      dataKey: 'interestExpenseTrailing',
      yAxisId: 'leftAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, showLineReference: true },
    right: { type: 'bil', piecewise: true },
  },
};
export let customPerfPTC7 = {
  type: 'perf7',
  year: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'ROIC',
      dataKey: 'roic',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Lãi suất vay',
      dataKey: 'laiVay',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, dash1: true, divide: 2 },
    right: { type: 'per', piecewise: true, dash2: true },
  },
};
export let customPerfPTC8 = {
  type: 'perf8',
  year: false,
  series: [
    {
      type: 'line',
      label: 'Biên lợi nhuận ròng TTM',
      dataKey: 'nimgTrailing',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Vòng quay tài sản',
      dataKey: 'assetTurnover',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'Đòn bẩy',
      dataKey: 'leverage',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: '(Nợ + VCSH)/VCSH',
      dataKey: 'dee',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, divide: 1 },
    right: { type: 'time', piecewise: true, dash3: true },
  },
};

export let customBalPTC1 = {
  type: 'bal1',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Tiền',
      dataKey: 'tienDTNGDaoHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Phải thu',
      dataKey: 'phaiThu',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Hàng tồn kho',
      dataKey: 'hangTonKhoRong',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tài sản cố định',
      dataKey: 'taiSanCoDinh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tài sản dở dang',
      dataKey: 'taiSanDoDangDaiHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#2471BE',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Bất động sản đầu tư',
      dataKey: 'giaTriRongTaiSanDauTu',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#585D5D',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tài sản khác',
      dataKey: 'taiSanKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, legendNum: 3 },
    right: { type: 'bil', piecewise: false, showLineReference: true },
  },
};
export let customBalPTC2 = {
  type: 'bal2',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn góp của Chủ sở hữu',
      dataKey: 'vonGop',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#585D5D',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'LNST chưa phân phối',
      dataKey: 'laiChuaPhanPhoi',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu khác',
      dataKey: 'vcshKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ chiếm dụng',
      dataKey: 'noChiemDung',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ vay',
      dataKey: 'noVay',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#AD5757',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, legendNum: 2 },
    right: { type: 'bil', piecewise: false, showLineReference: true },
  },
};
export let customBalPTC3 = {
  type: 'bal3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Nguyên giá tài sản cố định',
      dataKey: 'grossPPE',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khấu hao lũy kế',
      dataKey: 'dappe',
      yAxisId: 'rightAxis',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Chi phí xây dựng cơ bản dở dang',
      dataKey: 'xayDungCoBanDoDang',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#2471BE',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true, showLineReference: true },
  },
};
export let customBalPTC4 = {
  type: 'bal4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Nợ ròng',
      dataKey: 'netDebt',
      yAxisId: 'rightAxis',
      color: '#AD5757',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Vốn lưu động',
      dataKey: 'workingcap',
      yAxisId: 'rightAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true, showLineReference: true },
  },
};
export let customBalPTC5 = {
  type: 'bal5',
  year: false,
  series: [
    {
      type: 'line',
      label: 'Vòng quay hàng tồn kho',
      dataKey: 'vongQuayHangTonKho',
      yAxisId: 'rightAxis',
      curve: 'linear',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'Vòng quay phải thu khách hàng',
      dataKey: 'vongQuayPhaiThu',
      yAxisId: 'rightAxis',
      curve: 'linear',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'bar',
      label: 'Vòng quay phải trả nhà cung cấp',
      dataKey: 'vongQuayPhaiTra',
      yAxisId: 'rightAxis',
      color: '#AD5757',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'time', piecewise: false },
  },
};
export let customBalPTC6 = {
  type: 'bal6',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Vay ngắn hạn/VCSH',
      dataKey: 'vayNganHanVCSH',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'bar',
      label: 'Vay dài hạn/VCSH',
      dataKey: 'vayDaiHanVCSH',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Vay/VCSH',
      dataKey: 'vayVCSH',
      yAxisId: 'rightAxis',
      curve: 'linear',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Lãi suất vay',
      dataKey: 'laiVay',
      yAxisId: 'leftAxis',
      curve: 'linear',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, marker: 2, divide: 3 },
    right: { type: 'per', piecewise: true, showLineReference: true },
  },
};

export let customCFPTC1 = {
  type: 'cf1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Hoạt động kinh doanh',
      dataKey: 'luuChuyenTienTeRongTuCacHoatDongSanXuatKinhDoanh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Hoạt động đầu tư',
      dataKey: 'luuChuyenTienTeRongTuCacHoatDongDauTu',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Hoạt động tài chính',
      dataKey: 'luuChuyenTienTeTuHoatDongTaiChinh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Dòng tiền tự do',
      dataKey: 'fcf',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#2471BE',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true, showLineReference: true },
  },
};
export let customCFPTC2 = {
  type: 'cf2',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Net Income + DA - NWC',
      dataKey: 'netIncomeDANWC',
      yAxisId: 'leftAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Net Income + DA - NWC - CAPEX',
      dataKey: 'netIncomeDANWCCAPEX',
      yAxisId: 'leftAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Net Income + DA - NWC (tích lũy)',
      dataKey: 'netIncomeDANWCRolling',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Net Income + DA - NWC - CAPEX (tích lũy)',
      dataKey: 'netIncomeDANWCCAPEXRolling',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: true, showLineReference: true, divide: 2, legendNum: 1 },
    right: { type: 'bil', piecewise: false, showLineReference: true },
  },
};
export let customCFPTC3 = {
  type: 'cf3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Nợ vay',
      dataKey: 'noVay',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#AD5757',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền và tương đương tiền',
      dataKey: 'tienVaTuongDuongTien',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Đầu tư tài chính ngắn hạn',
      dataKey: 'giaTriThuanDauTuNganHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'HTM dài hạn',
      dataKey: 'dauTuNamGiuDenNgayDaoHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Nợ ròng',
      dataKey: 'netDebt',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true, showLineReference: true },
  },
};
export let customCFPTC4 = {
  type: 'cf4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Người mua trả tiền trước ngắn hạn',
      dataKey: 'nguoiMuaTraTienTruoc',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Doanh thu chưa thực hiện ngắn hạn',
      dataKey: 'doanhThuChuaThucHienNganHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Người mua trả tiền trước dài hạn',
      dataKey: 'nguoiMuaTraTienTruocDaiHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Doanh thu chưa thực hiên dài hạn',
      dataKey: 'doanhThuChuaThucHien',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, legendNum: 1 },
    right: { type: 'bil', piecewise: false },
  },
};

export let customValPTC1 = {
  type: 'val1',
  year: false,
  series: [
    {
      type: 'line',
      label: 'P/E',
      dataKey: 'pe',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/E trung vị',
      dataKey: 'peMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'EV/EBITDA',
      dataKey: 'evebitda',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'EV/EBITDA trung vị',
      dataKey: 'evebitdaMedian',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'time', piecewise: false, dash1: true, divide: 2 },
    right: { type: 'time', piecewise: false, dash3: true },
  },
};
export let customValPTC2 = {
  type: 'val2',
  year: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'P/B',
      dataKey: 'pb',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/B trung vị',
      dataKey: 'pbMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, divide: 1 },
    right: { type: 'time', piecewise: true, dash2: true },
  },
};
export let customValPTC3 = {
  type: 'val3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu thuần TTM',
      dataKey: 'salettm',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'marketcap',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'bil', piecewise: true },
  },
};
export let customValPTC4 = {
  type: 'val4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu thuần TTM',
      dataKey: 'salettm',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'P/S',
      dataKey: 'ps',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/S trung vị',
      dataKey: 'psMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'time', piecewise: true, dash2: true },
  },
};
export let customValPTC5 = {
  type: 'val5',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận ròng TTM',
      dataKey: 'nittm',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'marketcap',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'bil', piecewise: true },
  },
};
export let customValPTC6 = {
  type: 'val6',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận ròng TTM',
      dataKey: 'nittm',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'P/E',
      dataKey: 'pe',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/E trung vị',
      dataKey: 'peMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'time', piecewise: false, dash2: true },
  },
};
export let customValPTC7 = {
  type: 'val7',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'EBITDA TTM',
      dataKey: 'ebitdattm',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'EV/EBITDA',
      dataKey: 'evebitda',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'EV/EBITDA trung vị',
      dataKey: 'evebitdaMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'time', piecewise: false, dash2: true },
  },
};
export let customValPTC8 = {
  type: 'val8',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu trừ Lợi ích CĐTS',
      dataKey: 'capital',
      yAxisId: 'leftAxis',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'marketcap',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'bil', piecewise: true },
  },
};
