export let customPerfCK1 = {
  type: 'perf1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu thuần',
      dataKey: 'doanhSoThuan',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận ròng',
      dataKey: 'loiNhuanCuaCoDongCongTyMe',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Biên lãi gộp',
      dataKey: 'bienLaiGop',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Biên lãi ròng',
      dataKey: 'bienLaiRong',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: true, divide: 2 },
    right: { type: 'per', piecewise: false },
  },
};
export let customPerfCK2 = {
  type: 'perf2',
  year: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#013368',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'ROA',
      dataKey: 'roa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#013368',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    // {
    //   type: 'line',
    //   label: 'ROIC',
    //   dataKey: 'roic',
    //   curve: 'linear',
    //   yAxisId: 'leftAxis',
    //   valueFormatter: (v) => (!v ? '' : v + ' %'),
    // },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, divide: 1 },
    right: { type: 'per', piecewise: true, dash1: true },
  },
};
export let customPerfCK3 = {
  type: 'perf3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận hoạt động',
      dataKey: 'loiNhuanCotLoi',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận tài chính',
      dataKey: 'loiNhuanTaiChinh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận khác',
      dataKey: 'thuNhapKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
export let customPerfCK4 = {
  type: 'perf4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Doanh thu TTM',
      dataKey: 'salesTrailing',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Lợi nhuận gộp TTM',
      dataKey: 'gpmtrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Chi phí vận hành TTM',
      dataKey: 'sgamtrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'EBIT Margin TTM',
      dataKey: 'ebitmTrailing',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CFAB6D',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'per', piecewise: true },
  },
};
export let customPerfCK5 = {
  type: 'perf5',
  year: false,
  series: [
    // {
    //   type: 'line',
    //   label: 'ROE',
    //   dataKey: 'roe',
    //   curve: 'linear',
    //   yAxisId: 'leftAxis',
    //   color: '#013368',
    //   valueFormatter: (v) => (!v ? '' : v + ' %'),
    // },
    {
      type: 'line',
      label: 'Biên lợi nhuận ròng TTM',
      dataKey: 'nimgTrailing',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Vòng quay tài sản',
      dataKey: 'assetTurnover',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'Đòn bẩy',
      dataKey: 'leverage',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: '(Nợ + VCSH)/VCSH',
      dataKey: 'dee',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, divide: 1 },
    right: { type: 'time', piecewise: false, dash3: true },
  },
};

export let customBalCK1 = {
  type: 'bal1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Vay/VCSH',
      dataKey: 'vayVCSH',
      yAxisId: 'rightAxis',
      color: '#013368',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Lãi suất vay',
      dataKey: 'laiVay',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#981F36',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, divide: 1 },
    right: { type: 'per', piecewise: false },
  },
};
export let customBalCK2 = {
  type: 'bal2',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Tiền',
      dataKey: 'tienVaTaiSanTuongDuongTien',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'FVTPL',
      dataKey: 'cacTaiSanTaiChinhThongQuaGhiNhanLaiLo',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'HTM',
      dataKey: 'cacKhoanDauTuNamGiuDenNgayDaoHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay',
      dataKey: 'cacKhoanChoVay',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'AFS',
      dataKey: 'cacKhoanTaiChinhSanSangDeBan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tài sản khác',
      dataKey: 'taiSanKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: false },
  },
};
export let customBalCK3 = {
  type: 'bal3',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn góp của chủ sở hữu',
      dataKey: 'coPhieuPhoThongCoQuyenBieuQuyet',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#585D5D',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'LNST chưa phân phối',
      dataKey: 'loiNhuanChuaPhanPhoi',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'VCSH khác',
      dataKey: 'vcshKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#ABB2B4',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ chiếm dụng',
      dataKey: 'noChiemDung',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ vay',
      dataKey: 'noVay',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#AD5757',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
export let customBalCK4 = {
  type: 'bal4',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'FVTPL',
      dataKey: 'laiTuCacTaiSanTaiChinhGhiNhanThongQuaLaiLo',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay và phải thu',
      dataKey: 'laiTuCacKhoanChoVayVaPhaiThu',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Môi giới chứng khoán',
      dataKey: 'doanhThuNghiepVuMoiGioiChungKhoan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'HTM',
      dataKey: 'laiTuCacKhoanDauTuNamGiuDenNgayDaoHan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'AFS',
      dataKey: 'laiTuCacTaiSanTaiChinhSanSangDeBan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Bảo lãnh phát hành',
      dataKey: 'doanhThuNghiepVuBaoLanhPhatHanhChungKhoan',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#CFAB6D',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khác',
      dataKey: 'tongDoanhThuKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
export let customBalCK5 = {
  type: 'bal5',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'FVTPL',
      dataKey: 'gpfvtpl',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay và phải thu',
      dataKey: 'gpcvmargin',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Môi giới chứng khoán',
      dataKey: 'gpmoiGioi',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'HTM',
      dataKey: 'gphtm',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'AFS',
      dataKey: 'gpafs',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Bảo lãnh phát hành',
      dataKey: 'gpbaoLanhPhatHanh',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#CFAB6D',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khác',
      dataKey: 'gpkhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};

export let customValCK1 = {
  type: 'val1',
  year: false,
  chart: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#013368',
      valueFormatter: (v) => (!v ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'P/B',
      dataKey: 'pb',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/B trung vị',
      dataKey: 'pbMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, divide: 1 },
    right: { type: 'time', piecewise: true, dash2: true },
  },
};
export let customValCK2 = {
  type: 'val2',
  year: false,
  chart: false,
  series: [
    {
      type: 'line',
      label: 'P/E',
      dataKey: 'pe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/E trung vị',
      dataKey: 'peMedian',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (!v ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'time', piecewise: false, dash1: true },
    right: { type: 'time', piecewise: false },
  },
};
export let customValCK3 = {
  type: 'val3',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận ròng TTM',
      dataKey: 'loiNhuanRongTTM',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'vonHoa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
export let customValCK4 = {
  type: 'val4',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu trừ Lợi ích CĐTS',
      dataKey: 'vonChuSoHuu',
      yAxisId: 'leftAxis',
      color: '#ABB2B4',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'vonHoa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};

export let customOtherCK1 = {
  type: 'other1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tiền gửi của khách hàng',
      dataKey: 'tienGuiCuaKhachHang',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay ký quỹ (margin)',
      dataKey: 'choVayKyQuy',
      yAxisId: 'leftAxis',
      color: '#93B6D6',
      valueFormatter: (v) => (!v ? '' : v.toLocaleString() + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: false },
  },
};
