export let customNHPerf1 = {
  type: 'perf1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tổng thu nhập hoạt động',
      dataKey: 'tongThuNhapHoatDong',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lợi nhuận ròng',
      dataKey: 'coDongCuaCongTyMe',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Biên lãi ròng',
      dataKey: 'bienLaiRong',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#0D6B64',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 2 },
    right: { type: 'per', piecewise: true },
  },
};
export let customNHPerf2 = {
  type: 'perf2',
  year: false,
  series: [
    {
      type: 'bar',
      label: '%Chi phí hoạt động',
      dataKey: 'cphoatDongTTNHD',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'bar',
      label: '%Chi phí dự phòng',
      dataKey: 'cpduPhongTTNHD',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: '%Tổng chi phí',
      dataKey: 'tongCPTTNHD',
      yAxisId: 'leftAxis',
      curve: 'linear',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: true, marker: 2 },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHPerf3 = {
  type: 'perf3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Thu nhập từ lãi',
      dataKey: 'thuNhapLaiThuan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Thu nhập từ dịch vụ',
      dataKey: 'laiLoTHuanTuHoatDongDichVu',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Thu nhập khác',
      dataKey: 'laiKhac',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHPerf4 = {
  type: 'perf4',
  year: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'ROA',
      dataKey: 'roa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, divide: 1 },
    right: { type: 'per', piecewise: true, dash1: true },
  },
};

export let customNHBal1 = {
  type: 'bal1',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tiền gửi và cho vay TCTD khác',
      dataKey: 'tgvaChoVayCacTCTDKhacTruocDuPhong',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay khác hàng',
      dataKey: 'choVayKhachHang',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Chứng khoán',
      dataKey: 'chungKhoanTruocDP',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tài sản khác',
      dataKey: 'cacTaiSanKhac',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal2 = {
  type: 'bal2',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tiền gửi và vay TCTD khác',
      dataKey: 'tienGuiVaVayCacToChucTinDung',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền gửi của khách hàng',
      dataKey: 'tienGuiCuaKhachHang',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Giấy tờ có giá',
      dataKey: 'phatHanhGiayToCoGia',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu',
      dataKey: 'vonChuSoHuu',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#585D5D',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ phải trả khác',
      dataKey: 'noPhaiTraKhac',
      yAxisId: 'rightAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: false },
  },
};
export let customNHBal3 = {
  type: 'bal3',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tăng trưởng tính dụng',
      dataKey: 'tinDungSVDauNam',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'bar',
      label: 'Tăng trưởng huy động vốn',
      dataKey: 'huyDongSVDauNam',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal4 = {
  type: 'bal4',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'COF',
      dataKey: 'chiPhiHuyDong',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'bar',
      label: 'NIM',
      dataKey: 'bienLaiThuan',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Tỉ lệ CASA',
      dataKey: 'tyLeCasa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'per', piecewise: false, divide: 2 },
    right: { type: 'per', piecewise: true },
  },
};
export let customNHBal5 = {
  type: 'bal5',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Tài sản có khác',
      dataKey: 'taiSanCoKhac',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Lãi, phí phải thu',
      dataKey: 'cacKhoanLaiPhiPhaiThu',
      yAxisId: 'leftAxis',
      color: '#8F9596',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'TS có khác/TTS',
      dataKey: 'tscoKhacTongTS',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'LPPT/CVKH',
      dataKey: 'laiPhiPhaiThuChoVayKhachHang',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 2 },
    right: { type: 'per', piecewise: false, dash3: true },
  },
};
export let customNHBal6 = {
  type: 'bal6',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Nợ xấu',
      dataKey: 'noXau',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Nợ nhóm 2',
      dataKey: 'noCanLuuY',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Tỉ lê nợ nhóm 2',
      dataKey: 'noN2ChoVayKhachHang',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'Tỉ lê nợ xấu',
      dataKey: 'tyLeNoXau',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 2 },
    right: { type: 'per', piecewise: true },
  },
};
export let customNHBal7 = {
  type: 'bal7',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Nợ xấu',
      dataKey: 'noXau',
      yAxisId: 'leftAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Dự phòng rủi ro',
      dataKey: 'duPhongRuiRoChoVayKhachHang',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Tỉ lệ dự phòng bảo phủ nợ xấu',
      dataKey: 'duPhongBaoNoXau',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: true, showLineReference: true, divide: 2 },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal8 = {
  type: 'bal8',
  year: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu',
      dataKey: 'vonChuSoHuu',
      yAxisId: 'leftAxis',
      color: '#585D5D',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Tỉ lệ nợ quá hạn/VCSH',
      dataKey: 'noN25VCSH',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#981F36',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, divide: 1 },
    right: { type: 'per', piecewise: true },
  },
};
export let customNHBal9 = {
  type: 'bal9',
  year: true,
  series: [
    {
      type: 'bar',
      label: 'Cho vay ngắn hạn',
      dataKey: 'choVayNganHan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay trung hạn',
      dataKey: 'choVayTrungHan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cho vay dài hạn',
      dataKey: 'choVayDaiHan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal10 = {
  type: 'bal10',
  year: true,
  series: [
    {
      type: 'bar',
      label: 'Doanh nghiệp nhà nước',
      dataKey: 'doanhNghiepNhaNuoc',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Công ty TNHH và cổ phần',
      dataKey: 'congTyTNHHVaCoPhan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Doanh nghiệp nước ngoài',
      dataKey: 'doanhNghiepNuocNgoai',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Hợp tác xã và công ty tư nhân',
      dataKey: 'hopTacXaVaCongTyTuNhan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cá nhân',
      dataKey: 'caNhan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khác',
      dataKey: 'khac',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, legendNum: 2 },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal11 = {
  type: 'bal11',
  year: true,
  series: [
    {
      type: 'bar',
      label: 'Tiền gửi không kỳ hạn',
      dataKey: 'tienGuiKhongKyHan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền gửi có kỳ hạn',
      dataKey: 'tienGuiCoKyHan',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#93B6D6',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền gửi tiết kiệm',
      dataKey: 'tienGuiTietKiem',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền gửi ký quỹ',
      dataKey: 'tienGuiKyQuy',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Tiền gửi cho những mục đích riêng biệt',
      dataKey: 'tienGuiChoNhungMucDichRiengBiet',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false, legendNum: 2 },
    right: { type: 'per', piecewise: false },
  },
};
export let customNHBal12 = {
  type: 'bal12',
  year: true,
  series: [
    {
      type: 'bar',
      label: 'Doanh nghiệp nhà nước',
      dataKey: 'doanhNghiepNhaNuocTG',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Doanh nghiệp tư nhân',
      dataKey: 'doanhNghiepTuNhanTG',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Doanh nghiệp nước ngoài',
      dataKey: 'doanhNghiepNuocNgoaiTG',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Cá nhân',
      dataKey: 'caNhanTG',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'bar',
      label: 'Khác',
      dataKey: 'khacTG',
      yAxisId: 'leftAxis',
      stack: 'stack',
      color: '#202222',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'per', piecewise: false },
  },
};

export let customNHVal1 = {
  type: 'val1',
  year: false,
  series: [
    {
      type: 'line',
      label: 'ROE',
      dataKey: 'roe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#013368',
      valueFormatter: (v) => (v === null ? '' : v + ' %'),
    },
    {
      type: 'line',
      label: 'P/B',
      dataKey: 'pb',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CC8C32',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/B trung vị',
      dataKey: 'pbMedian',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#CCBA95',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'per', piecewise: true, dash2: true },
  },
};
export let customNHVal2 = {
  type: 'val2',
  year: false,
  series: [
    {
      type: 'line',
      label: 'P/E',
      dataKey: 'pe',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
    {
      type: 'line',
      label: 'P/E trung vị',
      dataKey: 'peMedian',
      curve: 'linear',
      yAxisId: 'leftAxis',
      color: '#6EA2DF',
      valueFormatter: (v) => (v === null ? '' : v + ' lần'),
    },
  ],
  yAxis: {
    left: { type: 'time', piecewise: false },
    right: { type: 'per', piecewise: true, dash1: true },
  },
};
export let customNHVal3 = {
  type: 'val3',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Lợi nhuận ròng TTM',
      dataKey: 'loiNhuanRongTTM',
      yAxisId: 'leftAxis',
      color: '#C8D0D2',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'vonHoa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
export let customNHVal4 = {
  type: 'val4',
  year: false,
  chart: false,
  series: [
    {
      type: 'bar',
      label: 'Vốn chủ sở hữu',
      dataKey: 'vonChuSoHuu',
      yAxisId: 'leftAxis',
      color: '#ABB2B4',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
    {
      type: 'line',
      label: 'Vốn hóa',
      dataKey: 'vonHoa',
      curve: 'linear',
      yAxisId: 'rightAxis',
      color: '#014388',
      valueFormatter: (v) => (v === null ? '' : v + ' tỷ đồng'),
    },
  ],
  yAxis: {
    left: { type: 'bil', piecewise: false },
    right: { type: 'bil', piecewise: true },
  },
};
